import type { Metadata } from "next";
import Navbar from '../components/navbar/navbar'
import { inter, bungee, hairline, marker } from "./fonts";
import "./globals.css";
import 'bootstrap-icons/font/bootstrap-icons.css'



export const metadata: Metadata = {
  title: "Unofficial Audio Rarities",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={bungee.className}>
        {/* <Navbar></Navbar> */}
        {children}
      </body>
    </html>
  );
}
